### ISSUE TITLE
Config not working. >:(

### ISSUE THREAD

**Issue by snaildos** [real2two/dashactyl#15]
"link": "https://discord.com/api/oauth2/authorize?client_id=604245652624506881&redirect_uri=https%3A%2F%2Fsnaildos.com&response_type=code&scope=identify%20guilds%20guilds.join%20connections%20email",
        "callbackpath": "/callback",

![image](https://user-images.githubusercontent.com/46210117/117908084-7c37ab00-b30a-11eb-96d1-6dd0d0f1a0c5.png)

**Comment by Jax-Danger** [comment]
try using "callback" without the "/"
