### ISSUE TITLE
ui looks rubbish - let me fix it

### ISSUE THREAD

**Issue by elinarbur** [real2two/dashactyl#5]
the current ui is bad at best, ill fix it up for you for free with tailwindcss when ive got time. you might also want to look into next.js it makes everything 10x easier.

i can make a new ui folder or smth / make a new branch - whatever floats your boat.

if you need proof of me being competent ill just link a couple of sites ive made before

- https://www.icevm.co.uk/
- https://web.archive.org/web/20201205220919/https:/www.heimsnet.eu/
- https://www.arctictel.com/

ive also made the ui for the icevm control panel. it is not up right now but i can supply screenshots upon request.

respectfully, kjartan
for email inquiries: kjartan@icevm.co.uk

**Comment by dudeisbrendan03** [comment]
Just make a pr, don't come along to random repos adding issues

**Comment by elinarbur** [comment]
If you dont want it i wont do it then
